# 不指定镜像，使用GitLab Runner默认环境

stages:
  - build
  - test
  - deploy

# 缓存配置
cache:
  paths:
    - target/

# 构建阶段
build-job:
  stage: build
  script:
    - echo "编译项目..."
    - echo "构建完成！"
  artifacts:
    paths:
      - target/
    expire_in: 1 week

# 测试阶段
test-job:
  stage: test
  script:
    - echo "运行测试..."
    - echo "测试通过！"
  dependencies:
    - build-job

# 部署阶段
deploy-job:
  stage: deploy
  script:
    - echo "准备部署应用..."
    - echo "部署成功！"
  dependencies:
    - build-job
  only:
    - master

# 环境变量
variables:
  APP_VERSION: "1.0.0"
  APP_NAME: "moti-cloud" 