services:
  # MySQL数据库服务
  mysql:
    image: mysql:5.7
    container_name: moti-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: motipassword # 请修改为您自己的密码
      MYSQL_DATABASE: moti-cloud
    volumes:
      - mysql_data:/var/lib/mysql
      - ./moti-cloud.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # FTP服务
  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: moti-ftp
    restart: always
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftpuser # 请修改为您自己的FTP用户名
      FTP_USER_PASS: ftppassword # 请修改为您自己的FTP密码
      FTP_USER_HOME: /home/ftpusers/ftpuser
    volumes:
      - ftp_data:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

  # 莫提网盘应用
  moti-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moti-cloud
    restart: always
    depends_on:
      - mysql
      - ftp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/moti-cloud?serverTimezone=Hongkong&useAffectedRows=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=motipassword # 与MySQL密码保持一致
      - FTP_HOST=ftp
      - FTP_PORT=21
      - FTP_USERNAME=ftpuser # 与FTP用户名保持一致
      - FTP_PASSWORD=ftppassword # 与FTP密码保持一致
      - MAIL_USERNAME=您的QQ邮箱 # 请修改为您自己的QQ邮箱
      - MAIL_PASSWORD=您的QQ邮箱密码 # 请修改为您自己的QQ邮箱密码

volumes:
  mysql_data:
  ftp_data: 