server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: moti-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务API
        - id: moti-user
          uri: lb://moti-user
          predicates:
            - Path=/user/**
        # 文件服务API  
        - id: moti-file-api
          uri: lb://moti-file
          predicates:
            - Path=/file/**
        # 管理页面
        - id: file-admin-pages
          uri: lb://moti-file
          predicates:
            - Path=/u-admin/**
        # 文件服务内部API
        - id: file-internal-api
          uri: lb://moti-file
          predicates:
            - Path=/api/**
        # 主页面路由
        - id: web-pages
          uri: lb://moti-file
          predicates:
            - Path=/,/index,/login,/register,/logout,/admin,/temp-file
        # 静态资源
        - id: static-resources
          uri: lb://moti-file
          predicates:
            - Path=/static/**,/css/**,/js/**,/img/**,/plug-ins/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.moti: debug 